# Generated by Django 4.2.1 on 2023-07-31 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=46)),
                ('last_name', models.CharField(max_length=46)),
                ('full_name', models.CharField(editable=False, help_text='Please do not edit or delete this. Your changes here will not be saved.', max_length=93)),
                ('patient_id', models.DecimalField(decimal_places=0, max_digits=9)),
                ('enter_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('food_cosher', models.BooleanField(blank=True, default=None, null=True)),
                ('food_diary_restricted', models.BooleanField(blank=True, default=None, null=True)),
            ],
            options={
                'unique_together': {('patient_id',)},
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.PositiveIntegerField()),
                ('spo2', models.PositiveIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_view.patient')),
            ],
        ),
    ]
