# Generated by Django 4.2.1 on 2023-07-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default=None, help_text='Please do not edit or delete this. Your changes here will not be saved.', max_length=93),
        ),
    ]
